name: CI
on:
  pull_request:
    branches:
      - master

jobs:
  flutter_test:
    name: Run Flutter Test And Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-java@v2
        with:
          java-version: '12.x'
          distribution: 'temurin'  # أو 'adopt', 'zulu', إلخ
          
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          
      - run: flutter pub get
      
      - run: flutter analyze
      
      - run: flutter test
